#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ -d /var/www/cultibox ]; then
        echo " * Removing remaining file in /var/www/cultibox..."
        rm -Rf /var/www/cultibox
        echo "... OK"
    fi
    /usr/bin/mysql -u root -pcultibox -e "DROP DATABASE cultibox;" 2>/dev/null
fi

if [ "$1" == "remove" ]; then
    /usr/bin/mysql -u root -pcultibox -e "DROP DATABASE cultibox;" 2>/dev/null
fi

sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/cultipi/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/chown/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/cat/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/fswebcam/d" /etc/sudoers
