#!/bin/bash

echo "  * Configuring/checking Cultibox environment..."

chown -R www-data:www-data /var/www/cultibox

if [ ! -f /tmp/cultibox_upgrade ]; then
    echo "  * Installing the Cultibox software..."
    lang=`echo $LANG`
    case "$lang" in
        fr_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_fr.sql
            ;;
        en_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_en.sql
            ;;
        it_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_it.sql
            ;;
        de_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_de.sql
            ;;
        es_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_es.sql
            ;;
        *)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_fr.sql
            ;;
    esac
    /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/fake_log.sql

    echo "... OK"
else 
    echo "  * Upgrading the Cultibox's databases, this may take several minutes, please be patient..."
    /var/www/cultibox/run/get_version.sh > /tmp/cultibox_version
    if [ -f /tmp/cultibox_version ]; then
        #Get previous cultibox version
        version=`cat /tmp/cultibox_version`
        #Removing architecture information
        version=`echo ${version%%-*}`
        version=`echo ${version//./}`

        if [ "$version" != "" ]; then
            for file in `ls /var/www/cultibox/sql_install/update_sql-* 2>/dev/null`; do
               #Remove path file information
               file_name=`basename $file`
               #Remove extension information
               file_name=` echo ${file_name%.*}`
               #Get version information
               file_name=`echo $file_name|awk -F"-" '{print $2}'`
               file_name=`echo ${file_name//./}`

               if [ "$file_name" != "" ]; then
                    #if file version >= version
                    if [ $file_name -ge $version ]; then
                        /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/etc/my-extra.cnf --force -f -h 127.0.0.1 --port=3891 < $file 
                    fi
               fi
            done
        fi
        rm /tmp/cultibox_version
    fi

    if [ -f /var/www/cultibox/sql_install/update_sql.sql ]; then
        /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf --force -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/update_sql.sql 2>/dev/null
    fi

    rm -f /tmp/cultibox_upgrade
    if [ -f /tmp/cultibox_version ]; then
        rm /tmp/cultibox_version
    fi
    rm -f /var/www/cultibox/main/templates_c/*.ser 2>/dev/null
    echo "... OK"
fi
