#!/bin/bash

sed -i "s/; thread \/usr\/local\/etc\/thread1.conf/thread \/etc\/culticam\/thread1.conf/g" /etc/motion/motion.conf
sed -i "s/; thread \/usr\/local\/etc\/thread2.conf/thread \/etc\/culticam\/thread2.conf/g" /etc/motion/motion.conf
sed -i "s/; thread \/usr\/local\/etc\/thread3.conf/thread \/etc\/culticam\/thread3.conf/g" /etc/motion/motion.conf
sed -i "s/; thread \/usr\/local\/etc\/thread4.conf/thread \/etc\/culticam\/thread4.conf/g" /etc/motion/motion.conf
sed -i "s/daemon off/daemon on/g" /etc/motion/motion.conf
sed -i "s/webcam_localhost on/webcam_localhost off/g" /etc/motion/motion.conf

for i in 0 1 2 3; do
    if [ -f /etc/culticam/webcam${i}.conf ]; then
        j="`expr $i + 1`"
        width="`/bin/grep resolution /etc/culticam/webcam${i}.conf |/usr/bin/awk -F' ' '{print $2}'|/usr/bin/awk -F 'x' '{print $1}'`"
        height="`/bin/grep resolution /etc/culticam/webcam${i}.conf |/usr/bin/awk -F' ' '{print $2}'|/usr/bin/awk -F 'x' '{print $2}'`"
        title="`/bin/grep 'title' /etc/culticam/webcam${i}.conf |awk -F'\"' '{print $2}'`"
        brightness="`/bin/grep 'set brightness' /etc/culticam/webcam${i}.conf |awk -F'=' '{print $2}'`"
        contrast="`/bin/grep 'set contrast' /etc/culticam/webcam${i}.conf |awk -F'=' '{print $2}'`"
        palette="`/bin/grep 'palette' /etc/culticam/webcam${i}.conf |awk -F' ' '{print $2}'`"

        case palette in
            "MJPEG" )
                palette=2
            ;;
            "JPEG" )
                palette=3
            ;;
            "RGB3" )
                palette=4
            ;;
            "UYVY" )
                palette=5
            ;;
            "YUYV" )
                palette=6
            ;;
            "YU12" )
                palette=8
            ;;
            *)
                palette=8
            ;;
        esac

        sed -i "s/^width .*/width $width/g" /etc/culticam/thread${j}.conf
        sed -i "s/^height .*/height $height/g" /etc/culticam/thread${j}.conf
        sed -i "s/^text_left .*/text_left $title/g" /etc/culticam/thread${j}.conf
        sed -i "s/^v4l2_palette .*/v4l2_palette $palette/g" /etc/culticam/thread${j}.conf
    fi
done
sed -i "s/start_motion_daemon=no/start_motion_daemon=yes/g" /etc/default/motion

update-rc.d -f motion remove

