#!/bin/bash

if [ -d /tmp/cultibox_backup/mysql ]; then
    echo "  * An old saved of your Cultibox has been found, restoring datas..."
    cp -R /tmp/cultibox_backup/mysql /Applications/cultibox/xamppfiles/var/
    echo "... OK!"
fi


echo "  * Configuring your CultiBox environment..."
if [ ! -L /Applications/XAMPP ]; then
    ln -s /Applications/cultibox /Applications/XAMPP
fi

if [ -d /Applications/cultibox/cultibox.app ]; then
    mv /Applications/cultibox/cultibox.app /Applications/
fi

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`

chown -R $user_culti:$group_culti /Applications/cultibox
sed -i '' "s/User nobody/User $user_culti/" /Applications/cultibox/xamppfiles/etc/httpd.conf
sed -i '' "s/Group nogroup/Group $group_culti/" /Applications/cultibox/xamppfiles/etc/httpd.conf
chown -R nobody /Applications/cultibox/xamppfiles/var/mysql
chmod -R 775 /Applications/cultibox/xamppfiles/var/mysql

/Applications/XAMPP/xamppfiles/xampp restart
sleep 5
echo "... OK!"
if [ ! -d /tmp/cultibox_backup/mysql ]; then
    echo "  * Configuring your Cultibox software..."
    /Applications/XAMPP/xamppfiles/bin/mysqladmin -u root -h localhost password cultibox
    sleep 2
    /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/user_cultibox.sql
    /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/joomla.sql
    lang=`defaults read /Library/Preferences/.GlobalPreferences AppleLanguages| tr -d [:space:] | cut -c2-3`
    if [ "$lang" == "En" ]; then
        /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/cultibox_en.sql
    elif [ "$lang" == "Fr" ]; then
        /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/cultibox_fr.sql
    elif [ "$lang" == "De" ]; then
	    /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/cultibox_de.sql
    elif [ "$lang" == "It" ]; then
	    /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/cultibox_it.sql
    elif [ "$lang" == "Es" ]; then
        /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/cultibox_es.sql
    else
	    /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/cultibox_en.sql
    fi
    /Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/XAMPP/sql_install/fake_log.sql
    echo "... OK!"
else
    echo "  * Upgrading the Cultibox software configuration..."
    if [ -f /Applications/cultibox/sql_install/update_sql.sql ]; then
        /Applications/cultibox/xamppfiles/bin/mysql -f -u root -h localhost --port=3891 -pcultibox < /Applications/cultibox/sql_install/update_sql.sql 2>/dev/null
    fi
    /Applications/cultibox/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox -e "DROP DATABASE cultibox_joomla;"
    /Applications/cultibox/xamppfiles/bin/mysql -u root -h localhost --port=3891 -pcultibox < /Applications/cultibox/sql_install/joomla.sql
    rm -Rf /tmp/cultibox_backup
    rm -f /Applications/cultibox/xamppfiles/htdocs/cultibox/main/templates_c/*.ser 2>/dev/null
    echo "... OK!"
fi

echo "  * Installing CultiBox as a service..."
mv /Applications/cultibox/package/cultibox_apache.plist /System/Library/LaunchDaemons/
mv /Applications/cultibox/package/cultibox_mysql.plist /System/Library/LaunchDaemons/
chown root:wheel /System/Library/LaunchDaemons/cultibox_*.plist
chmod 644 /System/Library/LaunchDaemons/cultibox_*.plist
echo "... OK!"

echo "  * Restarting the CultiBox interface..."
/Applications/XAMPP/xamppfiles/xampp restart
echo "... OK!"
