#!/bin/bash

echo "   * Configuring your CultiBox environment..."
if [ ! -L /Applications/XAMPP ]; then
    ln -s /Applications/cultibox /Applications/XAMPP
fi

/Applications/XAMPP/xamppfiles/xampp stop

if [ -d /Applications/cultibox/cultibox.app ]; then
    mv /Applications/cultibox/cultibox.app /Applications/
fi

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`

chown -R $user_culti:$group_culti /Applications/cultibox
sed -i '' "s/User nobody/User $user_culti/" /Applications/cultibox/xamppfiles/etc/httpd.conf
sed -i '' "s/Group nogroup/Group $group_culti/" /Applications/cultibox/xamppfiles/etc/httpd.conf
sed -i "s/apache_server_port=80/apache_server_port=6891/" /Applications/cultibox/xamppfiles/properties.ini
sed -i "s/apache_user=daemon/apache_user=$user_culti/" /Applications/cultibox/xamppfiles/properties.ini
sed -i "s/apache_group=daemon/apache_group=$group_culti/" /Applications/cultibox/xamppfiles/properties.ini
sed -i "s/mysql_port=3306/mysql_port=3891/" /Applications/cultibox/xamppfiles/properties.ini

chown -R mysql /Applications/cultibox/xamppfiles/var/mysql
/Applications/XAMPP/xamppfiles/lampp start

sleep 4
echo "... OK"

if [ ! -f /tmp/cultibox_upgrade ]; then
    echo "   * Configuring your Cultibox software..."
    /Applications/XAMPP/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox

    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/user_cultibox.sql
    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/joomla.sql
    lang=`defaults read /Library/Preferences/.GlobalPreferences AppleLanguages| tr -d [:space:] | cut -c2-3`
    if [ "$lang" == "En" ]; then
        /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/cultibox_en.sql
    elif [ "$lang" == "Fr" ]; then
        /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/cultibox_fr.sql
    elif [ "$lang" == "De" ]; then
	    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/cultibox_de.sql
    elif [ "$lang" == "It" ]; then
	    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/cultibox_it.sql
    elif [ "$lang" == "Es" ]; then
        /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/cultibox_es.sql
    else
	    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/cultibox_en.sql
    fi
    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/fake_log.sql
    echo "...OK"
else
    echo "   * Upgrading the Cultibox software configuration..."
    /Applications/XAMPP/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
    /Applications/XAMPP/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/user_cultibox.sql

    /Applications/XAMPP/xamppfiles/load.sh
    sleep 2

    if [ -f /Applications/XAMPP/sql_install/update_joomla.sql ]; then
        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -f -h 127.0.0.1 --port=3891 < /Applications/XAMPP/sql_install/update_joomla.sqll
    fi


    if [ -f /tmp/cultibox_version ]; then
        #Get previous cultibox version
        version=`cat /tmp/cultibox_version`
        #Removing architecture information
        version=`echo ${version%%-*}`
        if [ "$version" != "" ]; then
            for file in `ls /Applications/XAMPP/sql_install/update_joomla-* 2>/dev/null`; do
               #Remove path file information
               file_name=`basename $file`
               #Remove extension information
               file_name=` echo ${file_name%.*}`
               #Get version information
               file_name=`echo $file_name|awk -F"-" '{print $2}'`
               file_name=`echo ${file_name//./}`

               if [ "$file_name" != "" ]; then
                    #if file version >= version
                    if [ $file_name -ge $version ]; then
                        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -f -h 127.0.0.1 --port=3891 < $file
                    fi
               fi
            done

            for file in `ls /Applications/XAMPP/sql_install/update_sql-* 2>/dev/null`; do
               #Remove path file information
               file_name=`basename $file`
               #Remove extension information
               file_name=` echo ${file_name%.*}`
               #Get version information
               file_name=`echo $file_name|awk -F"-" '{print $2}'`
               file_name=`echo ${file_name//./}`

               if [ "$file_name" != "" ]; then
                    #if file version >= version
                    if [ $file_name -ge $version ]; then
                        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -f -h 127.0.0.1 --port=3891 < $file
                    fi
               fi
            done
        fi
        rm /tmp/cultibox_version
    fi

    if [ -f /Applications/cultibox/sql_install/update_sql.sql ]; then
        /Applications/cultibox/xamppfiles/bin/mysql -f -u root -h 127.0.0.1 --port=3891 -pcultibox < /Applications/cultibox/sql_install/update_sql.sql 
    fi

    rm /tmp/cultibox_upgrade
    rm -f /Applications/cultibox/xamppfiles/htdocs/cultibox/main/templates_c/*.ser 2>/dev/null
    echo "...OK"
fi

echo "   * Installing CultiBox as a service..."
mv /Applications/cultibox/package/cultibox_apache.plist /System/Library/LaunchDaemons/
mv /Applications/cultibox/package/cultibox_mysql.plist /System/Library/LaunchDaemons/
chown root:wheel /System/Library/LaunchDaemons/cultibox_*.plist
chmod 644 /System/Library/LaunchDaemons/cultibox_*.plist
echo "...OK"

echo "   * Restarting the CultiBox interface..."
/Applications/XAMPP/xamppfiles/xampp restart
sleep 4
echo "...OK"
