#!/bin/bash

if [ -f /Applications/cultibox/xamppfiles/etc/php.ini ] && [ ! -f  /Applications/cultibox/xamppfiles/xampp ]; then
    echo " === An old version of the Cultibox seems to be remaining in your system, please remove manually the remaining Cultibox system in /Applications directory ===="
    exit 1
else
    if [ -d /Applications/cultibox ]; then
        /Applications/cultibox/xamppfiles/xampp start
        sleep 6

        # Upgrade case:
        if [ ! -f /Applications/cultibox/xamppfiles/etc/my-extra.cnf ]; then
          file=`find /var/folders/ -name "my-extra.cnf"|head -1`
          if [ "$file" != "" ]; then
            cp "$file" /Applications/cultibox/xamppfiles/etc/
          fi
        fi

        if [ -f /Applications/cultibox/run/get_version.sh ]; then
            if [ -f /tmp/cultibox_version ]; then
                rm /tmp/cultibox_version
            fi
            /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
        else 
          file=`find /var/folders/ -name "get_version.sh"`
          if [ "$file" != "" ]; then
            cp "$file" /Applications/cultibox/run/
          fi
        fi

        touch /tmp/cultibox_upgrade

        if [ -f /Applications/cultibox/run/backup.sh ]; then
            file=`find /var/folders/ -name "backup.sh" -anewer /Applications/cultibox/run/backup.sh`
            if [ "$file" != "" ]; then
                cp "$file" /Applications/cultibox/run/
            fi
            
            /Applications/cultibox/run/backup.sh
            if [ $? -ne 0 ]; then
                echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting ===="
                exit 1
            fi
        else 
            file=`find /var/folders/ -name "backup.sh"`
            if [ "$file" != "" ]; then
                cp "$file" /Applications/cultibox/run
            fi
        fi
    fi
fi
