#!/bin/bash


if [ -f /Applications/cultibox/xamppfiles/etc/php.ini ] && [ ! -f  /Applications/cultibox/xamppfiles/lampp ]; then
    echo "An old version of the Cultibox seems to be remaining in your system, please remove manually the remaining Cultibox system in /Applications directory"
    exit 1
else
   if [ -d /Applications/cultibox ]
        if [ -f /Applications/cultibox/get_version.sh ]; then
            if [ -f /tmp/cultibox_version ]; then
                rm /tmp/cultibox_version
            fi
            /Applications/cultibox/get_version.sh > /tmp/cultibox_version
        fi
        touch /tmp/cultibox_upgrade
    fi
fi




