#!/bin/bash

if [ -f /Applications/cultibox/xamppfiles/etc/php.ini ] && [ ! -f  /Applications/cultibox/xamppfiles/xampp ]; then
    echo " === An old version of the Cultibox seems to be remaining in your system, please remove manually the remaining Cultibox system in /Applications directory ===="
    exit 1
else
    if [ -f /tmp/cultibox_upgrade ]; then
        rm -f /tmp/cultibox_upgrade
    fi
 
    if [ -d /Applications/cultibox ]; then
        cat > /Applications/cultibox/xamppfiles/etc/my-extra.cnf << "EOF" 
[client]
user="root"
password="cultibox"
EOF
        cat > /Applications/cultibox/run/get_version.sh << "EOF"
#!/bin/bash

set -e

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`
home=`egrep "^$user_culti" /etc/passwd|awk -F":" '{print $6}'`

# Test of the connection:
/Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 cultibox -e "SELECT * FROM  configuration;" > /dev/null 2>&1
if [ $? -eq 0 ]; then
        result=`/Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 --batch cultibox -e "SELECT VERSION FROM configuration;"`
        for res in `echo $result`; do
            if [ "`echo $res|egrep [1-9].*\.[1-9].*\.[1-9].*-.*`" != "" ]; then
                echo $res
                exit 0
            fi
        done
else
        exit 1
fi
exit 0
EOF
      chmod +x /Applications/cultibox/run/get_version.sh
      /Applications/cultibox/xamppfiles/xampp stop
      sleep 6

      # Remaining process:
      if [ "`ps aux|grep httpd|grep cultibox`" != "" ] || [ "`ps aux|grep mysql|grep cultibox`" != "" ]; then
        for process in `ps aux|grep httpd| grep cultibox| awk -F" " '{print $2}'`; do
            kill -9 $process
        done

        for process in `ps aux|grep mysql| grep cultibox| awk -F" " '{print $2}'`; do
            kill -9 $process
        done
      fi

      /Applications/cultibox/xamppfiles/xampp start
      sleep 6
      if [ -f /Applications/cultibox/run/get_version.sh ]; then
          if [ -f /tmp/cultibox_version ]; then
              rm /tmp/cultibox_version
          fi

          cpt=0
          /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
          while [ $? -ne 0 ]; do
              if [ $cpt -ge 5 ];then
                  echo "==== Error during preinstall script, please check that the Cultibox software is correctly running, exiting ===="
                  exit 1
              fi
              cpt=`expr $cpt + 1`
              sleep 6
              /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
          done 
      fi

      /Applications/cultibox/xamppfiles/xampp stop
      sleep 6
      if [ -d /tmp/cultibox_backup ]; then
            rm -Rf /tmp/cultibox_backup
      fi

      mkdir -p /tmp/cultibox_backup
      cp -R /Applications/cultibox/xamppfiles/var/mysql/* /tmp/cultibox_backup/
      touch /tmp/cultibox_upgrade
    else 
        # Remaining process:
        if [ "`ps aux|grep httpd|grep cultibox`" != "" ] || [ "`ps aux|grep mysql|grep cultibox`" != "" ]; then
            for process in `ps aux|grep httpd| grep cultibox| awk -F" " '{print $2}'`; do
                kill -9 $process
            done

            for process in `ps aux|grep mysql| grep cultibox| awk -F" " '{print $2}'`; do
                kill -9 $process
            done
        fi
    fi
fi
