#!/bin/bash

if [ -d /opt/cultibox ]; then   
    /etc/init.d/cultibox start
    /opt/cultibox/run/backup.sh
    if [ $? -ne 0 ]; then
        echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting ===="
        exit 1
    fi
fi
exit 0
