ALTER TABLE `configuration` ADD `LOG_SEARCH` INT NOT NULL DEFAULT '2';
ALTER TABLE `configuration` CHANGE `COLOR_HUMIDITY_GRAPH` `COLOR_HUMIDITY_GRAPH` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'blue';
ALTER TABLE `configuration` CHANGE `COLOR_TEMPERATURE_GRAPH` `COLOR_TEMPERATURE_GRAPH` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'red';
ALTER TABLE `configuration` CHANGE `COLOR_POWER_GRAPH` `COLOR_POWER_GRAPH` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'black';
ALTER TABLE `configuration` CHANGE `COLOR_PROGRAM_GRAPH` `COLOR_PROGRAM_GRAPH` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'green';
UPDATE `configuration` SET `VERSION` = '1.0.264' WHERE `configuration`.`id` =1;
