#!/bin/bash
set -x

if [ -f /etc/init.d/culticam ]; then
    update-rc.d culticam defaults
fi

if [  "`cat /etc/sudoers|grep cultipi|grep fswebcam`" == "" ]; then
        echo "cultipi ALL = (root) NOPASSWD: /usr/bin/fswebcam" >> /etc/sudoers
fi  

chown -R cultipi:cultipi /opt/culticam
chown cultipi:cultipi /etc/init.d/culticam
chmod 744 /etc/init.d/culticam

/etc/init.d/culticam force-reload
