#!/bin/bash

if [ -f /opt/cultibox/etc/php.ini ] && [ ! -f  /opt/cultibox/lampp ]; then
    echo "An old version of the Cultibox seems to be remaining in your system, please execute the following command before installing a new Cultibox version:"
    echo "      dpkg --purge cultibox"
    exit 1
fi

if [ "$1" == "upgrade" ]; then
    if [ -d /opt/lampp/var/mysql/cultibox ]; then
        cp -R /opt/lampp/var/mysql/cultibox /opt/lampp/var/cultibox.save
    fi

    if [ -d /opt/lampp/var/mysql/cultibox_joomla ]; then
        cp -R /opt/lampp/var/mysql/cultibox_joomla /opt/lampp/var/cultibox_joomla.save
    fi

    if [ -f /opt/lampp/var/mysql/ibdata1 ]; then
        cp -R /opt/lampp/var/mysql/ibdata1 /opt/lampp/var/ibdata1.save
    fi
fi
