#!/bin/bash

if [ -d /opt/cultibox ]; then   
    /opt/lampp/backup.sh
    if [ $? -ne 0 ]; then
        echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting"
        exit 1
    fi
    /etc/init.d/cultibox stop
fi

if [ "$1" == "upgrade" ]; then
    #Update of the needed scripts to back up the environment:
    cat > /opt/cultibox/etc/my-extra.cnf << "EOF" 
[client]
user="root"
password="cultibox"
EOF

    cat > /opt/cultibox/backup.sh << "EOF" 
#!/bin/bash
set -e

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`
home=`egrep "^$user_culti" /etc/passwd|awk -F":" '{print $6}'`

echo "-----------------------------------------------------------------"
echo "              Cultibox backup database script                    "
echo "-----------------------------------------------------------------"
echo ""

if [ ! -d $home/.cultibox ]; then
    echo "  * Creating $home/.cultibox directory to store backup files"
    mkdir $home/.cultibox
    chown $user_culti:$group_culti $home/.cultibox
else
    echo "  * $home/.cultibox already exists and will be used to store backup files"
fi

echo "  * Exporting your current databae..."
/opt/lampp/bin/mysqldump --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 cultibox > $home/.cultibox/backup_cultibox.bak.new
if [ $? -eq 0 ]; then
    echo "... cultibox: OK"
else
    rm $home/.cultibox/backup_cultibox.bak.new
    echo "==== Error during the backup of the cultibox database, exiting ===="
    echo "... NOK"
    exit 1
fi

/opt/lampp/bin/mysqldump --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 cultibox_joomla > $home/.cultibox/backup_joomla.bak.new
if [ $? -eq 0 ]; then
    echo "... joomla: OK"
else
    rm $home/.cultibox/backup_joomla.bak.new
    echo "==== Error during the backup of the joomla database, exiting ===="
    echo "... NOK"
    exit 1
fi

#Saving the database in the directory $home/.cultibox:
echo "  * Saving previous Cultibox backup database..."
if [ -f $home/.cultibox/backup_cultibox.bak ]; then
    mv $home/.cultibox/backup_cultibox.bak $home/.cultibox/backup_cultibox.bak.old
    echo "... OK"
fi
echo "  * Saving previous Joomla backups database..."
if [ -f $home/.cultibox/backup_joomla.bak ]; then
    mv $home/.cultibox/backup_joomla.bak $home/.cultibox/backup_joomla.bak.old
    echo "... OK"
fi
mv $home/.cultibox/backup_cultibox.bak.new $home/.cultibox/backup_cultibox.bak
mv $home/.cultibox/backup_joomla.bak.new $home/.cultibox/backup_joomla.bak
chown $user_culti:$group_culti $home/.cultibox/*
exit 0
EOF


    cat > /opt/cultibox/get_version.sh << "EOF" 
#!/bin/bash

set -e

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`
home=`egrep "^$user_culti" /etc/passwd|awk -F":" '{print $6}'`

# Test of the connection:
/opt/lampp/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 cultibox -e "SELECT * FROM  configuration;" > /dev/null 2>&1
if [ $? -eq 0 ]; then
        result=`/opt/lampp/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 --batch cultibox -e "SELECT VERSION FROM configuration;"`
        for res in `echo $result`; do
            if [ "`echo $res|egrep [1-9].*\.[1-9].*\.[1-9].*-.*`" != "" ]; then
                echo $res
                exit 0
            fi
        done
else
        exit 1
fi
exit 0
EOF

    
    if [ -f /tmp/cultibox_version ]; then
        rm /tmp/cultibox_version
    fi
    /opt/cultibox/get_version.sh > /tmp/cultibox_version 
    touch /tmp/cultibox_upgrade
fi

exit 0
