SET CHARACTER SET utf8;

-- Version 1.1.29
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Documentation', 'Find a more complete documentation in the software by clicking on the Help tab <a href="http://localhost:6891/cultibox/main/docs/documentation_cultibox.pdf" target="_blank"> </ a>. The most current version is available using the following address:', NULL , 'https://code.google.com/p/cultibox', 'external', 'en_GB');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Some questions?', 'If help is not enough to answer one of your question, send us an email at the following address:', NULL , 'support@cultibox.fr', 'mail', 'en_GB');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Accessories', 'You can complete your package by purchasing additional sensors, 1000W and 3500W plugs or other accessories by visiting the website:', NULL , 'http://www.cultibox.fr', 'external', 'en_GB');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Recycling', 'At Cultibox we reprocess all part of our products. The packaging can be recycled and Cultibox contains a lithium battery that should not be thrown away. For optimal recycling, return us the Cultibox and you will be rewarded.', 'recycling.png', NULL , NULL , 'en_GB');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Warrantly', 'The Cultibox and accessories are warranted for two years. We ensure the security directly, without intermediary. To contact us:', NULL , 'support@cultibox.fr', 'mail', 'en_GB');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Documentación', 'Encuentra una documentación más completa en el software haciendo clic en la pestaña <a href="http://localhost:6891/cultibox/main/docs/documentation_cultibox.pdf" target="_blank">Ayuda </ a>. La versión más actualizada se encuentra disponible la siguiente dirección:', NULL , 'https://code.google.com/p/cultibox', 'external', 'es_ES');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , '¿Preguntas?', 'Si la ayuda no es suficiente para cumplir con una de sus preguntas, envíe un correo electrónico a la siguiente dirección:', NULL , 'support@cultibox.fr', 'mail', 'es_ES');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Accesorios', 'Puede completar su paquete mediante la compra de sensores adicionales, 1000W y 3500W accesorios tomadas u otro, visitando el sitio web:', NULL , 'http://www.cultibox.fr', 'external', 'es_ES');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Reciclaje', 'En Cultibox que reprocesar parte de nuestros productos. El embalaje es reciclable y Cultibox contiene una batería de litio que no debe ser desechada. Para un reciclaje óptimo, nos devuelven Cultibox y serás recompensado.', 'recycling.png', NULL , NULL , 'es_ES');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Garantía', 'El Cultibox y accesorios tienen una garantía de dos años. Garantizamos la seguridad directamente, sin intermediario. Para contactar con nosotros:', NULL , 'support@cultibox.fr', 'mail', 'es_ES');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Documentazione', 'Trova una documentazione più completa del software facendo clic sulla scheda <a href="http://localhost:6891/cultibox/main/docs/documentation_cultibox.pdf" target="_blank">Guida</a>. La versione più aggiornata è disponibile al seguente indirizzo:', NULL , 'https://code.google.com/p/cultibox', 'external', 'it_IT');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Domande?', 'Se l''aiuto non è sufficiente a soddisfare una delle vostre domande, inviateci una e-mail al seguente indirizzo:', NULL , 'support@cultibox.fr', 'mail', 'it_IT');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Accessori', 'È possibile completare il pacchetto con l''acquisto di sensori supplementari, 1000W e 3500W accessori adottate o altro visitando il sito:', NULL , 'http://www.cultibox.fr', 'external', 'it_IT');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Riciclaggio', 'In Cultibox abbiamo rielaborare tutti parte dei nostri prodotti. L''imballaggio può essere riciclato e Cultibox contiene una batteria al litio che non deve essere gettato via. Per il riciclaggio ottimale, noi tornare Cultibox e sarete ricompensati.', 'recycling.png', NULL , NULL , 'it_IT');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Garanzia', 'Il Cultibox e gli accessori sono garantiti per due anni. Noi garantiamo la sicurezza direttamente, senza intermediari. Per contattarci:', NULL , 'support@cultibox.fr', 'mail', 'it_IT');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Dokumentation', 'Finden Sie eine umfassendere Dokumentation in der Software, indem Sie auf der <a href="http://localhost:6891/cultibox/main/docs/documentation_cultibox.pdf" target="_blank"> Registerkarte Hilfe</ a>. Die aktuelle Version ist verfügbar unter folgender Adresse:', NULL , 'https://code.google.com/p/cultibox', 'external', 'de_DE');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Haben Sie Fragen?', 'Ist die Beihilfe ist nicht genug, um eine Ihrer Fragen gerecht zu werden, senden Sie uns eine E-Mail an die folgende Adresse:', NULL , 'support@cultibox.fr', 'mail', 'de_DE');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Zubehör', 'Sie können Ihr Paket durch den Kauf von zusätzlichen Sensoren, 1000W und 3500W genommen oder anderem Zubehör durch den Besuch der Website zu vervollständigen:', NULL , 'http://www.cultibox.fr', 'external', 'de_DE');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Recycling', 'In Cultibox wir nachbearbeiten alle Teil unserer Produkte. Die Verpackung kann recycelt werden und Cultibox enthält eine Lithium-Batterie, die nicht geworfen sollten entfernt werden. Für eine optimale Wiederverwertung, bringen uns Cultibox und Sie werden belohnt werden.', 'recycling.png', NULL , NULL , 'de_DE');
INSERT INTO `cultibox`.`notes` ( `id` , `title` , `desc` , `image` , `link` , `type_link` , `lang`) VALUES ( NULL , 'Garantie', 'Die Cultibox und Zubehör sind für zwei Jahre garantiert. Wir sorgen für die Sicherheit direkt, ohne Vermittler. Um uns zu kontaktieren:', NULL , 'support@cultibox.fr', 'mail', 'de_DE');

UPDATE `cultibox`.`notes` SET `title` = 'Recyclage' WHERE `notes`.`id` =4;
ALTER TABLE `cultibox`.`calendar` ADD `Icon` VARCHAR( 30 ) NULL ;

