var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dimanche",
            "mon": "Lundi",
            "tue": "Mardi",
            "wed": "Mercredi",
            "thu": "Jeudi",
            "fri": "Vendredi",
            "sat": "Samedi",
            "jan": "Janvier",
            "feb": "Février",
            "mar": "Mars",
            "apr": "Avril",
            "may": "Mai",
            "jun": "Juin",
            "jul": "Juillet",
            "aug": "Août",
            "sep": "Septembre",
            "oct": "Octobre",
            "nov": "Novembre",
            "dec": "Décembre"
        },
        "no_implemented": "Pas encore implémenté",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Non définie",
        "allday_event": "All day event",
        "repeat_event": "Répéter l'évènement",
        "time": "Date",
        "event": "Evènement",
        "location": "Lieu",
        "participant": "Participant",
        "get_data_exception": "Erreur lors de la récupération des données",
        "new_event": "Nouvel évènement",
        "confirm_delete_event": "Etes-vous certain de vouloir supprimer cet évènement? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Erreur dans le format des données! ",
        "invalid_title": "Le titre de l'évènement ne peut être vide ou contenir les caractères suivants ($<>)",
        "view_no_ready": "L'affichage n'est pas disponible",
        "example": "",
        "content": "Sujet",
        "create_event": "Créer un évènement",
        "update_detail": "Editer/Créer un évènement",
        "click_to_detail": "Afficher les détails",
        "i_delete": "Supprimer",
        "day_plural": "jours",
        "others": "Autre",
        "item": ""
    }
});
