#!/bin/bash
set -x

if [ -f /etc/init.d/cultitime ]; then
    update-rc.d cultitime defaults
fi

if [  "`cat /etc/sudoers|grep cultipi|grep date`" == "" ]; then
    echo "cultipi ALL = (root) NOPASSWD: /bin/date" >> /etc/sudoers
fi

chown -R cultipi:cultipi /opt/cultitime
chown cultipi:cultipi /etc/init.d/cultitime
chmod 644 /etc/init.d/cultitime

/etc/init.d/cultitime force-reload
