#!/bin/bash
set -x

if [ "$1" == "purge" ] || [ "$1" == "remove" ]; then
    if [ "`ps ax|grep cultiTime.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep cultiTime.tcl|grep tclsh|awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi

    update-rc.d -f cultitime remove >/dev/null 2>&1

    if [ -f /etc/init.d/cultitime ]; then
        rm -Rf /etc/init.d/cultitime
    fi
fi


sed -i "/cultipi ALL = (root) NOPASSWD: \/bin\/date/d" /etc/sudoers
