#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ -d /var/www/cultinet ]; then
        rm -Rf /var/www/cultinet
    fi

    sed -i "#www-data ALL = (root) NOPASSWD: /sbin/ifconfig#d" /etc/sudoers
    sed -i "#www-data ALL = (root) NOPASSWD: /sbin/iwlist#d" /etc/sudoers
    sed -i "#www-data ALL = (root) NOPASSWD: /sbin/ifup#d" /etc/sudoers
    sed -i "#www-data ALL = (root) NOPASSWD: /bin/mv#d" /etc/sudoers
    sed -i "#www-data ALL = (root) NOPASSWD: /bin/chmod#d" /etc/sudoers
    sed -i "#www-data ALL = (root) NOPASSWD: /bin/cp#d" /etc/sudoers
    sed -i "#www-data ALL = (root) NOPASSWD: /etc/init.d/networking#d" /etc/sudoers
fi


echo $1
echo "---------------"

exit 0
