#!/bin/bash

#Random sleep:
sleep $[ ( $RANDOM % 300 )  + 1 ]s

#If there was an error whith dpkg/apt:
/usr/bin/dpkg --configure -a

apt-get update -o Dir::Etc::sourcelist="sources.list.d/cultibox.list"  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

if [ -f /etc/apt/sources.list.d/cultibox-dev.list ]; then
    apt-get update -o Dir::Etc::sourcelist="sources.list.d/cultibox-dev.list"  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
fi

if [ "`apt-get -u upgrade --assume-no|grep cultipi`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultipi
elif [ "`dpkg -s cultipi 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultipi
fi

if [ "`apt-get -u upgrade --assume-no|grep cultibox`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultibox
    rm -Rf /var/cache/lighttpd/compress/*
    if [ "$1" == "" ]; then
        /etc/init.d/lighttpd force-reload
    fi
elif [ "`dpkg -s cultibox 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultibox
fi

if [ "`apt-get -u upgrade --assume-no|grep cultiraz`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultiraz
elif [ "`dpkg -s cultiraz 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultiraz
fi


if [ "`apt-get -u upgrade --assume-no|grep cultitime`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultitime
elif [ "`dpkg -s cultitime 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultitime
fi

if [ "`apt-get -u upgrade --assume-no|grep cultidoc`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultidoc
elif [ "`dpkg -s cultidoc 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultidoc
fi

if [ "`apt-get -u upgrade --assume-no|grep culticonf`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" culticonf
elif [ "`dpkg -s culticonf 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes culticonf
fi


if [ -d /var/www/cultibox/tmp/import ]; then
    rm -Rf /var/www/cultibox/tmp/import/*
fi

if [ -d /var/www/cultibox/tmp/export ]; then
    rm -Rf /var/www/cultibox/tmp/export/*
fi

if [ -f /tmp/PACKAGES-NEEDED ]; then
    packages="`cat /tmp/PACKAGES-NEDDED`"
    if [ "$packages" != "" ]; then
        apt-get update
        apt-get install -y --force-yes $packages
        apt-get clean
        rm -Rf /tmp/PACKAGES-NEEDED
    fi
fi

if [ -f /tmp/REBOOT-NEEDED ]; then
    rm -Rf /tmp/REBOOT-NEEDED
    shutdown -r now
fi

rm -Rf /tmp/*

uptime=$(</proc/uptime)
uptime=${uptime%%.*}

if [ "$uptime" != "" ]; then
    if [ $uptime -gt 604800 ]; then
        shutdown -r now
    fi
fi


/sbin/iw reg set FR

