#! /bin/sh -e

DAEMON="/opt/lampp/lampp" 
DEAMON_NAME="cultibox" 

PATH="/sbin:/bin:/usr/sbin:/usr/bin" 


test -x $DAEMON || exit 0

. /lib/lsb/init-functions


lampp_start () {
        log_daemon_msg "Starting system $DEAMON_NAME"
        $DAEMON start
        log_end_msg $?
}

lampp_stop () {
        log_daemon_msg "Stopping system $DEAMON_NAME"
        $DAEMON stop
        log_end_msg $?
}

lampp_restart () {
        log_daemon_msg "Stopping system $DEAMON_NAME"
        $DAEMON restart
        log_end_msg $?
}


case "$1" in
        start|stop)
                lampp_${1}
                ;;
        restart|reload|force-reload)
               lampp_restart
                ;;
        force-stop)
                lampp_stop
                killall -q $DEAMON_NAME || true
                sleep 2
                killall -q -9 $DEAMON_NAME || true
                ;;
        status)
               $DAEMON status
               ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
               ;;
esac
exit 0
