#!/bin/bash


if [ -f /etc/cron.daily/cultipi ]; then
    chmod 755 /etc/cron.daily/cultipi
    chown root:root /etc/cron.daily/cultipi
fi

if [ -f /etc/cron.hourly/cultipi ]; then
    chmod 755 /etc/cron.hourly/cultipi
    chown root:root /etc/cron.hourly/cultipi
fi

if [ -f /etc/default/cultipi ]; then
    chmod 644 /etc/default/cultipi
    chown root:root /etc/default/cultipi
fi

if [ ! -O /etc/logrotate.d/cultipi ] || [ ! -G /etc/logrotate.d/cultipi ]; then
    chown root:root /etc/logrotate.d/cultipi
    chmod 644 /etc/logrotate.d/cultipi
fi



if [ "`cat /etc/crontab|grep culticron`" == "" ]; then
    echo "*/1 *   * * *   root    /bin/bash /etc/default/culticron" >> /etc/crontab
fi


if [ -f /VERSION ]; then
    VERSION="`cat /VERSION`"
else
    VERSION=""
fi

if [ $VERSION -lt 150315 ]; then
    cat << EOF > /etc/rc.local
#!/bin/bash 

#Case of an adHoc network:
if [ "\`/bin/grep cultipi_ /etc/network/interfaces\`" != "" ]; then
    #Configuration of the captiv portal if it's not the case yet:
    if [ "\`/sbin/iptables -L -t nat | /bin/grep 10.0.0.100\`" == "" ]; then
        /sbin/iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j DNAT --to-destination 10.0.0.100:80
    fi
else
    #If it's not an adHoc network, deleteting captiv portal configuration:
    for i in \$(/sbin/iptables -t nat --line-numbers -L | /bin/grep ^[0-9] | /usr/bin/awk '{ print \$1 }' | /usr/bin/tac ); do /sbin/iptables -t nat -D PREROUTING \$i; done
fi

#To accelerate boot time, eth0 is not configured at boot time (due to the time DHCP uses to respond when a wire is not plugged).
#But we have to configure the interface if a wire is plugged:
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ]; then
    /sbin/ifup --force eth0
else
    /sbin/ifdown --force eth0
fi

#Configuration of the keymap in FR:
/usr/bin/loadkeys fr

exit 0
EOF

    cat << EOF > /etc/ifplugd/action.d/ifupdown
#!/bin/bash 

logger -t IFPLUGD: \$1 \$2

#For routes, we have to restart network:
route del default
if [ "\$2" == "up" ]; then
    if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ]; then
        /sbin/ifup --force eth0
    fi
else
    if [ "\`/sbin/ifconfig wlan0 2>/dev/null\`" != "" ]; then
        /sbin/ifdown --force wlan0
        sleep 1
        /sbin/ifup --force wlan0
    fi
    /sbin/ifdown --force eth0
fi
EOF

    cat << EOF > /etc/network/interfaces.BASE
# interfaces(5) file used by ifup(8) and ifdown(8)
#IFACE LO
auto lo
iface lo inet loopback

#IFACE ETH0
allow-hotplug eth0
iface eth0 inet dhcp

#IFACE WLAN0
auto wlan0
allow-hotplug wlan0
iface wlan0 inet static
address 10.0.0.100
netmask 255.0.0.0
wireless-channel 4
wireless-essid cultipi_network
wireless-mode ad-hoc
wireless-power off
post-up /etc/rc.local; /etc/init.d/isc-dhcp-server force-reload; /etc/init.d/dnsmasq force-reload
EOF

    if [ "`/bin/grep cultipi_ /etc/network/interfaces`" != "" ] && [ "`/bin/grep post-up /etc/network/interfaces`" == "" ]; then
        echo "post-up /etc/rc.local; /etc/init.d/isc-dhcp-server force-reload; /etc/init.d/dnsmasq force-reload" >> /etc/network/interfaces
    fi


    /bin/sed -i "s/ wlan0//" /etc/default/ifplugd 
    /bin/sed -i "s/wlan0//" /etc/default/ifplugd 
    /bin/sed -i "s/use-ipv6=yes/use-ipv6=no/" /etc/avahi/avahi-daemon.conf

    echo "options rt2800usb nohwcrypt=1" > /etc/modprobe.d/rt2800usb.conf

    echo "deb http://www.greenbox-botanic.com/cultibox/repository/armhf/ binary/" > /etc/apt/sources.list.d/cultibox.list
    if [ -f /etc/apt/sources.list.d/cultibox-dev.list ]; then
        echo "deb http://www.greenbox-botanic.com/cultibox/repository-dev/armhf/ binary/" > /etc/apt/sources.list.d/cultibox-dev.list
    fi

    #Upgrading image's version:
    echo "150315" > /VERSION

    #We need to reboot:
    touch /tmp/REBOOT-NEEDED 
fi

if [ $VERSION -lt 150328 ]; then
    /usr/sbin/adduser www-data i2c
    echo "150328" > /VERSION
fi

if [ $VERSION -lt 150330 ]; then
    if [  "`cat /etc/sudoers|grep www-data|grep fswebcam`" == "" ]; then
        sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/fswebcam/d" /etc/sudoers
    fi
    echo "150330" > /VERSION
fi


if [ $VERSION -ne 150402 ]; then
    if [  "`cat /etc/sudoers|grep www-data|grep iwconfig`" == "" ]; then
        sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/iwconfig/d" /etc/sudoers
    fi

    cat << EOF > /etc/network/interfaces.BASE
# interfaces(5) file used by ifup(8) and ifdown(8)
#IFACE LO
auto lo
iface lo inet loopback

#IFACE ETH0
allow-hotplug eth0
iface eth0 inet dhcp

#IFACE WLAN0
auto wlan0
allow-hotplug wlan0
iface wlan0 inet static
address 10.0.0.100
netmask 255.0.0.0
post-up /etc/rc.local; /etc/init.d/isc-dhcp-server force-reload; /etc/init.d/dnsmasq force-reload; /etc/init.d/hostapd force-reload
EOF

    echo "150402" > /VERSION

    echo "hostapd" > /tmp/PACKAGES-NEEDED
    cat << EOF > /tmp/hostapd
#/bin/bash

update-rc.d hostapd remove

echo "interface=wlan0" > /etc/hostapd/hostapd.conf
echo "ssid=cultipi_network" >> /etc/hostapd/hostapd.conf
echo "hw_mode=g" >> /etc/hostapd/hostapd.conf
echo "channel=4" >> /etc/hostapd/hostapd.conf
echo "auth_algs=1" >> /etc/hostapd/hostapd.conf
echo "wmm_enabled=0" >> /etc/hostapd/hostapd.conf

echo "DAEMON_CONF=\"/etc/hostapd/hostapd.conf\""  >> /etc/default/hostapd
EOF

fi

find /etc/default/ -name "*-dist"|xargs rm 2>/dev/null; echo ""


