#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ "`ps ax|grep cultipi|grep tclsh`" != "" ]; then
        for process in `ps ax|grep cultipi|grep tclsh|awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi

    if [ -d /opt/cultipi ]; then
        rm -Rf /opt/cultipi
    fi

    if [ -d /etc/cultipi ]; then
        rm -Rf /etc/cultipi
    fi

    update-rc.d -f cultipi remove >/dev/null 2>&1

    if [ -d /var/log/cultipi ]; then
        rm -Rf /var/log/cultipi
    fi

    if [ -f /etc/default/culticron ]; then
        rm /etc/default/culticron
    fi

    sed -i "/.*\/etc\/init.d\/cultipi.*/d" /etc/crontab
fi

if [ "$1" == "remove" ]; then
    if [ -f /etc/init.d/cultipi ]; then
        rm -Rf /etc/init.d/cultipi
    fi
    update-rc.d -f cultipi remove > /dev/null 2>&1 
    sed -i "/.*\/etc\/init.d\/cultipi.*/d" /etc/crontab

    if [ -d /opt/cultipi ]; then
        rm -Rf /opt/cultipi
    fi
fi
