#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    update-rc.d cultipi defaults
fi

if [ "`cat /etc/crontab|grep culticron`" == "" ]; then
    echo "*/1 *   * * *   root    /bin/bash /etc/default/culticron" >> /etc/crontab
fi

if [ ! -d /etc/cultipi/conf_tmp ]; then
    mkdir /etc/cultipi/conf_tmp
fi

if [ ! -d /etc/cultipi/conf_tmp/logs ]; then
    mkdir -p /etc/cultipi/conf_tmp/logs
fi

if [ ! -d /etc/cultipi/conf_tmp/cnf/plg ]; then
    mkdir -p /etc/cultipi/conf_tmp/cnf/plg
fi

if [ ! -d /etc/cultipi/conf_tmp/cnf/prg ]; then
    mkdir -p /etc/cultipi/conf_tmp/cnf/prg
fi

chown -R www-data:www-data /etc/cultipi/conf_tmp
chown -R cultipi:cultipi /var/log/cultipi
chmod 755 /var/log/cultipi

/etc/init.d/cultipi force-reload
