#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    update-rc.d cultipi defaults
    /etc/init.d/cultipi restart
fi

if [ ! -d /home/cultipi/logs ]; then
    mkdir /home/cultipi/logs
    chown cultipi:cultipi /home/cultipi/logs
fi

if [ -f /etc/cron.daily/cultipi ]; then
    chmod +x /etc/cron.daily/cultipi
fi

