#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ "`ps aux|grep cultipi|grep tclsh`" != "" ]; then
        for process in `ps aux|grep cultipi|grep tclsh|awk -F" " '{print $2}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi

    if [ -d /opt/cultipi ]; then
        rm -Rf /opt/cultipi
    fi

    if [ -d /etc/cultipi ]; then
        rm -Rf /etc/cultipi
    fi

    if [ -f /etc/init.d/cultipi ]; then
        update-rc.d -f cultipi remove
        rm -Rf /etc/init.d/cultipi
    fi

    if [ -d /var/log/cultipi ]; then
        rm -Rf /var/log/cultipi
    fi

    userdel cultipi
    sed -i "/cultipi ALL = (root) NOPASSWD: \/sbin\/modprobe/d" /etc/sudoers
fi

if [ "$1" == "remove" ]; then
    if [ -f /etc/init.d/cultipi ]; then
        update-rc.d -f cultipi remove
        rm -Rf /etc/init.d/cultipi
    fi
    sed -i "/cultipi ALL = (root) NOPASSWD: \/sbin\/modprobe/d" /etc/sudoers
    
    if [ -d /etc/cultipi ]; then
        rm -Rf /etc/cultipi
    fi
fi
