#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    /etc/init.d/cultipi stop
    sleep 2

    # Killing remaining process:
    if [ "`ps aux|grep cultipi|grep tclsh`" != "" ]; then
        for process in `ps aux|grep cultipi| grep tclsh| awk -F" " '{print $2}'`; do
            if [ "$process" != "" ]; then            
                kill -9 $process
            fi
        done
    fi

    if [ "`id cultipi 2>/dev/null`" == "" ]; then
        useradd --password raspberry cultipi
    fi
fi
exit 0
