#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    /etc/init.d/cultipi stop
    sleep 2

    # Killing remaining process:
    if [ "`ps aux|grep cultipi|grep tclsh`" != "" ]; then
        for process in `ps aux|grep cultipi| grep tclsh| awk -F" " '{print $2}'`; do
            if [ "$process" != "" ]; then            
                kill -9 $process
            fi
        done
    fi
fi

if [  "`cat /etc/sudoers|grep www-data|grep ifup`" == "" ]; then
    echo "cultipi ALL = (root) NOPASSWD: /sbin/modprobe" >> /etc/sudoers
fi

if [ "`id cultipi 2>/dev/null`" == "" ]; then
        useradd --password raspberry cultipi
fi
exit 0
