#!/bin/bash

if [ -d /var/cache/lighttpd/compress/cultibox ]; then
    rm -Rf /var/cache/lighttpd/compress/cultibox
fi

if [ -d /var/cache/lighttpd/compress/cultinet ]; then
    rm -Rf /var/cache/lighttpd/compress/cultinet
fi


apt-get update
apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultipi
apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultinet
apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultibox
apt-get clean
