#!/bin/bash

upgraded="False"
apt-get update -o Dir::Etc::sourcelist="sources.list.d/cultibox.list"  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"


if [ "`apt-get -u upgrade --assume-no|grep cultipi`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultipi
elif [ "`dpkg -s cultipi 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultipi
fi

if [ "`apt-get -u upgrade --assume-no|grep cultibox`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultibox
    upgraded="True"
elif [ "`dpkg -s cultibox 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultibox
fi

if [ "`apt-get -u upgrade --assume-no|grep cultiraz`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultiraz
elif [ "`dpkg -s cultiraz 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultiraz
fi


if [ "`apt-get -u upgrade --assume-no|grep cultitime`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" cultitime
elif [ "`dpkg -s cultitime 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultitime
fi

if [ "$upgraded" == "True" ]; then
    rm -Rf /var/cache/lighttpd/compress/*
    /etc/init.d/lighttpd force-reload
fi


if [ -d /var/www/cultibox/tmp/import ]; then
    rm -Rf /var/www/cultibox/tmp/import/*
fi

if [ -d /var/www/cultibox/tmp/export ]; then
    rm -Rf /var/www/cultibox/tmp/export/*
fi
