#!/bin/bash
set -x

echo "  * Configuring/checking Cultibox environment..."

chown -R www-data:www-data /var/www/cultibox

if [  "`cat /etc/sudoers|grep www-data|grep ifconfig`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/ifconfig" >> /etc/sudoers
fi
 
if [  "`cat /etc/sudoers|grep www-data|grep iwlist`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/sbin/iw" >> /etc/sudoers
fi
 
if [  "`cat /etc/sudoers|grep www-data|grep ifup`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/ifup" >> /etc/sudoers
fi
 
if [  "`cat /etc/sudoers|grep www-data|grep mv`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/mv" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep chmod`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/chmod" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep cp`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/cp" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep invoke-rc.d`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/sbin/invoke-rc.d" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep apt-get`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/bin/apt-get" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep isc-dhcp-server`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/isc-dhcp-server" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep dnsmasq`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/dnsmasq" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep iptables`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/iptables" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep date`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/date" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep rc.local`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/rc.local" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep modprobe`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/modprobe" >> /etc/sudoers
fi

if [ "`cat /etc/sudoers|grep cultipi|grep www-data`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/cultipi" >> /etc/sudoers
fi

if [ "`cat /etc/sudoers|grep chown|grep www-data`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/chown" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep cat`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/cat" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep shutdown`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/shutdown" >> /etc/sudoers
fi

if [ ! -f /tmp/cultibox_upgrade ]; then
    echo "  * Installing the Cultibox software..."
    lang=`echo $LANG`
    case "$lang" in
        fr_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_fr.sql
            ;;
        en_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_en.sql
            ;;
        it_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_it.sql
            ;;
        de_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_de.sql
            ;;
        es_*)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_es.sql
            ;;
        *)
            /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/cultibox_fr.sql
            ;;
    esac
    /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/fake_log.sql

    /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 cultibox -e "UPDATE sensors SET type=0  WHERE id > 1"

    echo "... OK"
else 
    echo "  * Upgrading the Cultibox's databases, this may take several minutes, please be patient..."
    if [ -f /var/www/cultibox/sql_install/update_sql.sql ]; then
        /usr/bin/mysql --defaults-extra-file=/var/www/cultibox/sql_install/my-extra.cnf --force -h 127.0.0.1 --port=3891 < /var/www/cultibox/sql_install/update_sql.sql 2>/dev/null
    fi

    rm -f /tmp/cultibox_upgrade
    rm -f /var/www/cultibox/main/templates_c/*.ser 2>/dev/null
    echo "... OK"
fi

find /var/www/cultibox/ -name "*-dist"|xargs rm 2>/dev/null; echo ""


if [ ! -d /home/cultipi/cultibox ]; then
    mkdir /home/cultipi/cultibox
    chown -R www-data:www-data /home/cultipi/cultibox
fi


