#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ -d /var/www/cultibox ]; then
        echo " * Removing remaining file in /var/www/cultibox..."
        rm -Rf /var/www/cultibox
        echo "... OK"
    fi
    /usr/bin/mysql -u root -pcultibox -e "DROP DATABASE cultibox;" 2>/dev/null
fi

if [ "$1" == "remove" ]; then
    /usr/bin/mysql -u root -pcultibox -e "DROP DATABASE cultibox;" 2>/dev/null
fi

sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/cultipi/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/chown/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/cat/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/shutdown/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/ifconfig/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/sbin\/iw/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/ifup/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/mv/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/chmod/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/cp/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/apt-get/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/dnsmasq/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/isc-dhcp-server/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/iptables/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/date/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/sbin\/invoke-rc.d/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/rc.local/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/modprobe/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/tail/d" /etc/sudoers
sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/lighttpd/d" /etc/sudoers

