#!/bin/bash
set -x

if [ "$1" == "purge" ] || [ "$1" == "remove" ]; then
    if [ "`ps ax|grep cultiRAZ.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep cultiRAZ.tcl|grep tclsh|awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi

    update-rc.d -f cultiraz remove >/dev/null 2>&1

    if [ -f /etc/init.d/cultiraz ]; then
        rm -Rf /etc/init.d/cultiraz
    fi
fi

