#! /bin/sh
### BEGIN INIT INFO
# Provides:          mjpg_streamer
# Required-Start:    $all 
# Required-Stop:     $all 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start mjpg_streamer daemon
# Description:       Enable mjpg_streamer service provided by daemon.
### END INIT INFO


PATH="/sbin:/bin:/usr/sbin:/usr/bin" 

DEAMON_NAME="mjpg_streamer"

. /lib/lsb/init-functions

if [ -f /var/lock/culticam_enable ]; then
	webcam="`cat /var/lock/culticam_enable`"
	. /etc/culticam/webcam$webcam.conf

	if [ "$BRIGHTNESS" != "" ] && [ $BRIGHTNESS -gt 0 ]; then
		BRIGHT="-br $BRIGHTNESS"
	else 
		BRIGHT=""
	fi
	
	if [ "$CONTRAST" != "" ] && [ $CONTRAST -gt 0 ]; then
		CON="-co $CONTRAST"
	else 
		CON=""
	fi
	
	args="-i \"/usr/lib/input_uvc.so -d $DEVICE -r $RESOLUTION $BRIGHT $CON -f 30 -n -y\" -o \"/usr/lib/output_http.so -p 8081\""
else 
	args="-i \"/usr/lib/input_uvc.so -d /dev/video0 -r 800x600 -f 30 -n -y\" -o \"/usr/lib/output_http.so -p 8081\""
fi

d_start () {
        log_daemon_msg "Starting system $DEAMON_NAME Daemon"
        nohup mjpg_streamer $args
		sleep 4
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $DEAMON_NAME Daemon"
        for pid in "`ps ax|grep mjpg_streamer |grep .so |awk -F " " '{print $1}'`"; do
            if [ "$pid" != "" ]; then
                kill -9 $pid
            fi
        done
        sleep 1
        log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;
        force-stop)
                d_stop
                ;;
        status)
                if [ "`ps ax|grep mjpg_streamer|grep '.so'`" != "" ]; then
                    echo "[ ok ] $DEAMON_NAME service is running..."
                    exit 0
                else 
                    echo "[ fail ] $DEAMON_NAME service is not running..."
                    exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
