#!/bin/bash

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`

if [ ! -f /opt/lampp ] && [ ! -L /opt/lampp ]; then
    ln -s /opt/cultibox /opt/lampp
fi

chown -R $user_culti:$group_culti /opt/cultibox
sed -i "s/User nobody/User $user_culti/" /opt/lampp/etc/httpd.conf
sed -i "s/Group nogroup/Group $group_culti/" /opt/lampp/etc/httpd.conf
sed -i "s/user*.*= nobody/user    = $user_culti/" /opt/lampp/etc/my.cnf

/opt/lampp/lampp restart

if [ ! -f /tmp/cultibox_upgrade ]; then
    /opt/lampp/bin/mysqladmin -u root -h localhost password cultibox

    /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/user_cultibox.sql
    /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/joomla.sql

    lang=`echo $LANG|grep -i fr`
    if [ "$lang" != "" ]; then
        /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/cultibox_fr.sql
    else
        /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/cultibox_en.sql
    fi

    /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/fake_log.sql

    cp /opt/lampp/daemon/cultibox /etc/init.d/
    chmod 755 /etc/init.d/cultibox
    update-rc.d cultibox defaults

    /opt/lampp/lampp restart
else 
    home=`egrep "^$user_culti" /etc/passwd|awk -F":" '{print $6}'`
    if [ -f /opt/lampp/sql_install/update_sql.sql ]; then
        /opt/lampp/bin/mysql -f -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/update_sql.sql 2>/dev/null
    fi
    /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox -e "DROP DATABASE cultibox_joomla;"
    /opt/lampp/bin/mysql -u root -h localhost --port=3891 -pcultibox < /opt/lampp/sql_install/joomla.sql
    /opt/lampp/lampp restart
    rm -f /tmp/cultibox_upgrade
    rm -f /opt/cultibox/htdocs/cultibox/main/templates_c/*.ser 2>/dev/null
fi

