#!/bin/bash

echo "  * Configuring/checking Cultibox environment..."
user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`

if [ ! -f /opt/lampp ] && [ ! -L /opt/lampp ]; then
    ln -s /opt/cultibox /opt/lampp
fi
chown -R $user_culti:$group_culti /opt/cultibox
sed -i "s/User nobody/User $user_culti/" /opt/cultibox/etc/httpd.conf
sed -i "s/Group nogroup/Group $group_culti/" /opt/cultibox/etc/httpd.conf
sed -i "s/user*.*= nobody/user    = $user_culti/" /opt/cultibox/etc/my.cnf
sed -i "s/apache_server_port=80/apache_server_port=6891/" /opt/cultibox/properties.ini
sed -i "s/apache_user=daemon/apache_user=$user_culti/" /opt/cultibox/properties.ini
sed -i "s/apache_group=daemon/apache_group=$group_culti/" /opt/cultibox/properties.ini
sed -i "s/mysql_port=3306/mysql_port=3891/" /opt/cultibox/properties.ini

if [ "`/usr/bin/getent group mysql`" == "" ]; then
    /usr/sbin/addgroup mysql
fi

if [ "`/usr/bin/getent passwd  mysql`" == "" ]; then
    /usr/sbin/useradd -d /home/mysql -M -s /bin/sh -g mysql mysql
fi


chown -R mysql /opt/cultibox/var/mysql

if [ ! -f /tmp/cultibox_upgrade ]; then
    /opt/cultibox/lampp restart
    sleep 6

    # Check if mysql is alive
    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        sleep 6
        /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 -u root -h 127.0.0.1 ping >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "==== Error, the mysql service doesn't seem to be started... exiting ===="
            exit 1
        fi
    fi
    echo "... OK"

    echo "  * Installing the Cultibox software..."
    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
    /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/user_cultibox.sql

    lang=`echo $LANG`
    case "$lang" in
        fr_*)
            /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/cultibox_fr.sql
            ;;
        en_*)
            /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/cultibox_en.sql
            ;;
        it_*)
            /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/cultibox_it.sql
            ;;
        de_*)
            /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/cultibox_de.sql
            ;;
        es_*)
            /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/cultibox_es.sql
            ;;
        *)
            /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/cultibox_fr.sql
            ;;
    esac
    /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/fake_log.sql

    cp /opt/cultibox/daemon/cultibox /etc/init.d/
    chmod 755 /etc/init.d/cultibox
    update-rc.d cultibox defaults

    /opt/cultibox/lampp restart
    sleep 2
    echo "... OK"
else 
    echo "  * A previous version of Cultibox was installed, upgrading your software..."
    if [ -d /tmp/cultibox_backup ]; then
        cp -R /tmp/cultibox_backup/* /opt/cultibox/var/mysql/
        rm -f /opt/cultibox/var/mysql/mysql/innodb_index_stats*
        rm -f /opt/cultibox/var/mysql/mysql/innodb_table_stats*
        rm -f /opt/cultibox/var/mysql/mysql/slave_master_info*
        rm -f /opt/cultibox/var/mysql/mysql/slave_relay_log_info*
        rm -f /opt/cultibox/var/mysql/mysql/slave_worker_info*
    else
        echo "==== Error, can't access to the cultibox backup directory... exiting ===="
        exit 1
    fi

    /opt/cultibox/lampp restart
    sleep 2

    # Check if mysql is alive
    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        sleep 4
        /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 -u root -h 127.0.0.1 ping >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "==== Error, the mysql service doesn't seem to be started... exiting ===="
            exit 1
        fi
    fi
    echo "... OK"

    echo "  * Upgrading the Cultibox's databases, this may take several minutes, please be patient..."
    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
    /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/user_cultibox.sql

    /opt/cultibox/run/get_version.sh > /tmp/cultibox_version
    if [ -f /tmp/cultibox_version ]; then
        #Get previous cultibox version
        version=`cat /tmp/cultibox_version`
        #Removing architecture information
        version=`echo ${version%%-*}`
        version=`echo ${version//./}`

        if [ "$version" != "" ]; then
            for file in `ls /opt/cultibox/sql_install/update_sql-* 2>/dev/null`; do
               #Remove path file information
               file_name=`basename $file`
               #Remove extension information
               file_name=` echo ${file_name%.*}`
               #Get version information
               file_name=`echo $file_name|awk -F"-" '{print $2}'`
               file_name=`echo ${file_name//./}`

               if [ "$file_name" != "" ]; then
                    #if file version >= version
                    if [ $file_name -ge $version ]; then
                        /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf --force -f -h 127.0.0.1 --port=3891 < $file 
                    fi
               fi
            done
        fi
        rm /tmp/cultibox_version
    fi

    if [ -f /opt/cultibox/sql_install/update_sql.sql ]; then
        /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf --force -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/update_sql.sql 2>/dev/null
    fi

    /opt/cultibox/lampp restart
    sleep 2
    rm -f /tmp/cultibox_upgrade
    if [ -f /tmp/cultibox_version ]; then
        rm /tmp/cultibox_version
    fi
    rm -f /opt/cultibox/htdocs/cultibox/main/templates_c/*.ser 2>/dev/null
    echo "... OK"
fi
