#!/bin/bash

if [ "$1" == "purge" ] || [ "$1" == "remove" ]; then
    if [ "`ps ax|grep cultiCam.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep cultiCam.tcl|grep tclsh|awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi

    update-rc.d -f culticam remove >/dev/null 2>&1

    if [ -f /etc/init.d/culticam ]; then
        rm -Rf /etc/init.d/culticam
    fi
fi

