alias wget_php='wget -O -'
alias cpilog='tail -f /var/log/cultipi/cultipi.log'
alias cpislog='tail -f /var/log/cultipi/cultipi-service.log'
alias cpireload='/etc/init.d/cultipi force-reload'
alias cpimysql='mysql -u cultibox -pcultibox cultibox '
