#!/bin/bash


if [ "$1" != "upgrade" ]; then
    if [ -f /etc/init.d/cultibox ]; then
        update-rc.d -f cultibox remove
        rm /etc/init.d/cultibox
    fi

    if [ -f /usr/share/applications/cultibox.desktop ]; then
        rm /usr/share/applications/cultibox.desktop
    fi

    if [ -L /opt/lampp ]; then
        rm /opt/lampp
    fi
fi

if [ "$1" == "purge" ]; then
    if [ -d /opt/cultibox ]; then
        rm -Rf /opt/cultibox
    fi

    if [ "`ps aux|grep cultibox`" != "" ]; then
        for process in `ps aux|grep cultibox|awk -F" " '{print $2}'`; do
            kill -9 $process
        done
    fi
fi
