#!/bin/bash

if [ -f /opt/cultibox/etc/php.ini ] && [ ! -f  /opt/cultibox/lampp ]; then
    echo "An old version of the Cultibox seems to be remaining in your system, please execute the following command before installing a new Cultibox version:"
    echo "      dpkg --purge cultibox"
    exit 1
fi

if [ "$1" == "upgrade" ]; then
    if [ -d /opt/cultibox/var/mysql/cultibox ]; then
        cp -R /opt/cultibox/var/mysql/cultibox /opt/cultibox/var/cultibox.save
    fi

    if [ -d /opt/cultibox/var/mysql/cultibox_joomla ]; then
        cp -R /opt/cultibox/var/mysql/cultibox_joomla /opt/cultibox/var/cultibox_joomla.save
    fi

    for line in `ls /opt/cultibox/var/mysql/ibdata* 2>/dev/null`; do
        cp $line /opt/cultibox/var/`basename $line`.save
    done 

    for line in `ls /opt/cultibox/var/mysql/ib_logfile* 2>/dev/null`; do
        cp $line /opt/cultibox/var/`basename $line`.save
    done
fi
