#!/bin/bash

if [ -d /opt/cultibox ]; then   
    /opt/lampp/backup.sh
    if [ $? -ne 0 ]; then
        echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting"
        exit 1
    fi
    /etc/init.d/cultibox stop
fi

if [ "$1" == "upgrade" ]; then
    if [ -f /opt/cultibox/get_version.sh ]; then
        if [ -f /tmp/cultibox_version ]; then
            rm /tmp/cultibox_version
        fi
        /opt/cultibox/get_version.sh > /tmp/cultibox_version 
    fi    
fi

exit 0
