#!/bin/bash

#Random sleep:
sleep $[ ( $RANDOM % 300 )  + 1 ]s

#If there was an error whith dpkg/apt:
/usr/bin/dpkg --configure -a --force-confdef --force-confold

apt-get update -o Dir::Etc::sourcelist="sources.list.d/cultibox.list"  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

for file in "`ls /etc/apt/sources.list.d/cultibox-*.list 2>/dev/null`"; do
    if [ "$file" != "" ]; then
        apt-get update -o Dir::Etc::sourcelist="$file" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
    fi
done

if [ "`apt-get -u upgrade --assume-no|grep cultipi`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" cultipi
elif [ "`dpkg -s cultipi 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultipi
fi

if [ "`apt-get -u upgrade --assume-no|grep cultibox`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" cultibox
    rm -Rf /var/cache/lighttpd/compress/*
    if [ "$1" == "" ]; then
        /etc/init.d/lighttpd force-reload
    fi
elif [ "`dpkg -s cultibox 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultibox
fi

if [ "`apt-get -u upgrade --assume-no|grep cultiraz`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" cultiraz
elif [ "`dpkg -s cultiraz 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultiraz
fi


if [ "`apt-get -u upgrade --assume-no|grep cultitime`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" cultitime
elif [ "`dpkg -s cultitime 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultitime
fi

if [ "`apt-get -u upgrade --assume-no|grep cultidoc`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" cultidoc
elif [ "`dpkg -s cultidoc 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes cultidoc
fi

if [ "`apt-get -u upgrade --assume-no|grep culticam`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" culticam
elif [ "`dpkg -s culticam 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes culticam
fi

if [ "`apt-get -u upgrade --assume-no|grep culticonf`" != "" ]; then
    apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" culticonf
elif [ "`dpkg -s culticonf 2>/dev/null|grep Version`" == "" ]; then
    apt-get install -y  --force-yes culticonf
fi



if [ -d /var/www/cultibox/tmp/import ]; then
    /m -Rf /var/www/cultibox/tmp/import/*
fi

if [ -d /var/www/cultibox/tmp/export ]; then
    rm -Rf /var/www/cultibox/tmp/export/*
fi

if [ "`ls /var/www/cultibox/tmp/webcam*.jpg 2>/dev/null`" != "" ]; then
    rm /var/www/cultibox/tmp/webcam*.jpg
fi

if [ -f /etc/culticonf/packages ]; then
    packages="`cat /etc/culticonf/packages`"
    if [ "$packages" != "" ]; then
        apt-get update
        for pack in $packages; do
            if [ "`dpkg -l $pack 2>/dev/null|grep ii`" == "" ]; then
                apt-get install -y --force-yes $pack

                if [ -f /etc/culticonf/postinst/$pack ]; then
                    bash /etc/culticonf/postinst/$pack
                fi
            fi
        done
        apt-get clean
    fi
fi

if [ -f /var/lock/REBOOT_NEEDED ]; then
    rm -Rf /var/lock/REBOOT_NEEDED
    shutdown -r now
fi

uptime=$(</proc/uptime)
uptime=${uptime%%.*}

if [ "$uptime" != "" ]; then
    if [ $uptime -gt 432000 ]; then
        shutdown -r now
    fi
fi


/sbin/iw reg set FR

if [ ! -f /tmp/UPGRADE ]; then
    nohup /bin/bash -c 'sleep 3600 && /etc/cron.daily/cultipi' >/dev/null 2>&1 &
    touch /tmp/UPGRADE
else
    rm -f /tmp/UPGRADE
fi


rm -Rf /tmp/*
