#!/bin/bash

function check_package_manager {
    count=0
    while [ "`ps ax|grep 'apt-'|grep -v 'grep'`" != "" ] || [ "`ps ax|grep dpkg|grep -v 'grep'`" != "" ];do
        sleep 3
        count=`expr $count + 1`

        if [ $count -gt 100 ]; then
            return 1
        fi
    done
    return 0
}


while [ $# -gt 0 ]
do
    case "$1" in
        (--now) now=yes;;
        (--manual) manual=yes;;
        (*)  break;;
    esac
    shift
done


if [ "$manual" != "yes" ]; then
    exec 2>&1
    exec > >(logger -t "culticron.daily")
fi

#Random sleep:
if [ "$now" != "yes" ]; then
    sleep $[ ( $RANDOM % 3600 )  + 1 ]s
fi

check_package_manager
if [ $? -eq 1 ]; then
    echo "--> Error, a package manager is already running... exiting"
    exit 1
fi


#If there was an error whith dpkg/apt:
/usr/bin/dpkg --configure -a --force-confdef --force-confold

echo "--> Updating repositories..."
apt-get update
echo "...ok"

for PACKAGE in cultipi cultibox cultiraz cultitime cultidoc culticam culticonf
do
    if [ "`apt-get -u upgrade --assume-no|grep $PACKAGE`" != "" ]; then
        echo "--> Upgrading $PACKAGE package..."
        sleep 2
        apt-get install -y  --force-yes --only-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confmiss" $PACKAGE
        echo "...ok"
    elif [ "`dpkg -s $PACKAGE 2>/dev/null|grep Version`" == "" ]; then
        echo "--> Installing $PACKAGE package..."
        sleep 2
        apt-get install -y  --force-yes $PACKAGE
        echo "...ok"
    else
        echo "--> $PACKAGE package is up-to-date"
    fi
done


if [ -d /var/www/cultibox/tmp/import ]; then
    echo "--> Cleaning import directory..."
    rm -Rf /var/www/cultibox/tmp/import/*
    echo "...ok"
fi

if [ -d /var/www/cultibox/tmp/export ]; then
    echo "--> Cleaning cultibox directory..."
    rm -Rf /var/www/cultibox/tmp/export/*
    echo "...ok"
fi

rm -Rf /var/www/cultibox/main/templates_c/*.ser 2>/dev/null


if [ -f /etc/culticonf/packages ]; then
    packages="`cat /etc/culticonf/packages`"
    if [ "$packages" != "" ]; then
        for pack in $packages; do
            if [ "`dpkg -l $pack 2>/dev/null|grep ii`" == "" ]; then
                echo "--> Installing package $pack..."
                sleep 2
				apt-get install -y --force-yes $pack
                echo "...ok"

                if [ -f /etc/culticonf/postinst/$pack ]; then
                    echo "--> Executing postinstall script for $pack"
                    bash /etc/culticonf/postinst/$pack
                    echo "...ok"
                fi
            fi
        done       
    fi
fi


/sbin/iw reg set FR

echo "--> Cleaning tmp directory..."
rm -Rf /tmp/*
echo "...ok"
	
if [ ! -f /var/lock/UPGRADE ]; then
    nohup /bin/bash -c 'sleep 3600 && /etc/cron.daily/cultipi --now' >/dev/null 2>&1 &
    touch /var/lock/UPGRADE
else
    rm -f /var/lock/UPGRADE
fi

uptime=$(</proc/uptime)
uptime=${uptime%%.*}
if [ -f /var/lock/REBOOT_NEEDED ]; then
    echo "--> Rebooting system by lock file..."
    rm -Rf /var/lock/REBOOT_NEEDED
    shutdown -r now
    echo "...ok"
elif [ "$uptime" != "" ]; then
    if [ $uptime -gt 432000 ]; then
        echo "--> Rebooting system by uptime..."
        shutdown -r now
        echo "...ok"
    fi
fi	
