#!/bin/bash

echo "Configuring your CultiBox environment:"
chown -R nobody:nogroup /Applications/XAMPP
/Applications/XAMPP/xamppfiles/xampp start
/Applications/XAMPP/xamppfiles/bin/mysqladmin -u root -h localhost password cultibox
/Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost -pcultibox < /Applications/XAMPP/sql_install/user_cultibox.sql
/Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost -pcultibox < /Applications/XAMPP/sql_install/joomla.sql
/Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost -pcultibox < /Applications/XAMPP/sql_install/cultibox.sql
/Applications/XAMPP/xamppfiles/bin/mysql -u root -h localhost -pcultibox < /Applications/XAMPP/sql_install/fake_log.sql

echo "Installing CultiBox as a service:"
echo "/Applications/XAMPP/xamppfiles/xampp start" > /etc/rc.local

echo "Restarting the CultiBox interface:"
/Applications/XAMPP/xamppfiles/xampp restart

