#!/bin/bash


echo "   * Configuring your CultiBox environment..."
if [ ! -L /Applications/XAMPP ]; then
    ln -s /Applications/cultibox /Applications/XAMPP
fi

/Applications/cultibox/xamppfiles/xampp stop

if [ -d /Applications/cultibox/cultibox.app ]; then
    if [ -d /Applications/cultibox.app ]; then
        rsync -a /Applications/cultibox.app /Applications/cultibox.app
        rm -Rf /Applications/cultibox/cultibox.app
    else 
        mv /Applications/cultibox/cultibox.app /Applications/
    fi
fi

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`

chown -R $user_culti:$group_culti /Applications/cultibox
sed -i '' "s/User daemon/User $user_culti/" /Applications/cultibox/xamppfiles/etc/httpd.conf
sed -i '' "s/Group daemon/Group $group_culti/" /Applications/cultibox/xamppfiles/etc/httpd.conf
sed -i '' "s/apache_server_port=80/apache_server_port=6891/" /Applications/cultibox/xamppfiles/properties.ini
sed -i '' "s/apache_user=daemon/apache_user=$user_culti/" /Applications/cultibox/xamppfiles/properties.ini
sed -i '' "s/apache_group=daemon/apache_group=$group_culti/" /Applications/cultibox/xamppfiles/properties.ini
sed -i '' "s/mysql_port=3306/mysql_port=3891/" /Applications/cultibox/xamppfiles/properties.ini

chown -R mysql /Applications/cultibox/xamppfiles/var/mysql
chown -R mysql /Applications/cultibox/xamppfiles/temp/mysql

if [ ! -f /tmp/cultibox_upgrade ]; then
    /Applications/cultibox/xamppfiles/xampp start
    sleep 6

    # Check if mysql is alive
    cpt=0
    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
    cpt=0
    while [ $? -ne 0 ]; do
        if [ $cpt -ge 5 ];then
            echo "==== Error, the mysql service doesn't seem be started... exiting ===="
            exit 1
        fi
        $cpt=`expr $cpt + 1`
        sleep 6
        /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
    done

    echo "   * Configuring your Cultibox software..."
    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
    if [ $? -ne 0 ]; then
        exit 1
    fi

    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/user_cultibox.sql
    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/joomla.sql
    lang=`defaults read /Library/Preferences/.GlobalPreferences AppleLanguages| tr -d [:space:] | cut -c2-3`
    if [ "$lang" == "En" ]; then
        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/cultibox_en.sql
    elif [ "$lang" == "Fr" ]; then
        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/cultibox_fr.sql
    elif [ "$lang" == "De" ]; then
	    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/cultibox_de.sql
    elif [ "$lang" == "It" ]; then
	    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/cultibox_it.sql
    elif [ "$lang" == "Es" ]; then
        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/cultibox_es.sql
    else
	    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/cultibox_en.sql
    fi
    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/fake_log.sql
    echo "...OK"
else
    echo "   * Upgrading the Cultibox software configuration..."
    if [ -d /tmp/cultibox_backup ]; then
        cp -R /tmp/cultibox_backup/* /Applications/cultibox/xamppfiles/var/mysql/
        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/innodb_index_stats*
        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/innodb_table_stats*
        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_master_info*
        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_relay_log_info*
        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_worker_info*
    else
        echo "==== Error, can't access to the cultibox backup directory... exiting ===="
        exit 1
    fi

    /Applications/cultibox/xamppfiles/xampp start
    sleep 6

    # Check if mysql is alive
    cpt=0
    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
    while [ $? -ne 0 ]; do
        if [ $cpt -ge 5 ];then
            echo "==== Error, the mysql service doesn't seem be started... exiting ===="
            exit 1
        fi
        $cpt=`expr $cpt + 1`
        sleep 6
        /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
    done


    echo "   * Configuring your Cultibox software..."
    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
    if [ $? -ne 0 ]; then
        exit 1
    fi

    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/user_cultibox.sql
    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 mysql < /Applications/cultibox/sql_install/five-tables.sql



    if [ -f /Applications/cultibox/sql_install/update_joomla.sql ]; then
        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/update_joomla.sql
    fi


    if [ -f /tmp/cultibox_version ]; then
        #Get previous cultibox version
        version=`cat /tmp/cultibox_version`
        #Removing architecture information
        version=`echo ${version%%-*}`
        version=`echo ${version//./}`

        if [ "$version" != "" ]; then
            for file in `ls /Applications/cultibox/sql_install/update_joomla-* 2>/dev/null`; do
               #Remove path file information
               file_name=`basename $file`
               #Remove extension information
               file_name=` echo ${file_name%.*}`
               #Get version information
               file_name=`echo $file_name|awk -F"-" '{print $2}'`
               file_name=`echo ${file_name//./}`

               if [ "$file_name" != "" ]; then
                    #if file version >= version
                    if [ $file_name -ge $version ]; then
                        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -f -h 127.0.0.1 --port=3891 < $file
                    fi
               fi
            done

            for file in `ls /Applications/cultibox/sql_install/update_sql-* 2>/dev/null`; do
               #Remove path file information
               file_name=`basename $file`
               #Remove extension information
               file_name=` echo ${file_name%.*}`
               #Get version information
               file_name=`echo $file_name|awk -F"-" '{print $2}'`
               file_name=`echo ${file_name//./}`

               if [ "$file_name" != "" ]; then
                    #if file version >= version
                    if [ $file_name -ge $version ]; then
                        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -f -h 127.0.0.1 --port=3891 < $file
                    fi
               fi
            done
        fi
        rm /tmp/cultibox_version
    fi

    if [ -f /Applications/cultibox/sql_install/update_sql.sql ]; then
        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/update_sql.sql 
    fi

    rm /tmp/cultibox_upgrade
    rm -Rf /tmp/cultibox_backup
    
    if [ -f /tmp/cultibox_version ]; then
        rm /tmp/cultibox_version
    fi

    rm -f /Applications/cultibox/xamppfiles/htdocs/cultibox/main/templates_c/*.ser 2>/dev/null
    echo "...OK"
fi

echo "   * Installing CultiBox as a service..."
mv /Applications/cultibox/package/cultibox_apache.plist /System/Library/LaunchDaemons/
mv /Applications/cultibox/package/cultibox_mysql.plist /System/Library/LaunchDaemons/
chown root:wheel /System/Library/LaunchDaemons/cultibox_*.plist
chmod 644 /System/Library/LaunchDaemons/cultibox_*.plist
echo "...OK"

echo "   * Restarting the CultiBox interface..."
/Applications/cultibox/xamppfiles/xampp restart
sleep 6
echo "...OK"
