#!/bin/bash

if [ -f /Applications/cultibox/xamppfiles/etc/php.ini ] && [ ! -f  /Applications/cultibox/xamppfiles/xampp ]; then
    echo " === An old version of the Cultibox seems to be remaining in your system, please remove manually the remaining Cultibox system in /Applications directory ===="
    exit 1
else
    if [ -f /tmp/cultibox_upgrade ]; then
        rm -f /tmp/cultibox_upgrade
    fi
 
         cat > /Applications/cultibox/xamppfiles/etc/my-extra.cnf << "EOF" 
[client]
user="root"
password="cultibox"
EOF

        cat > /Applications/cultibox/run/get_version.sh << "EOF"
#!/bin/bash

set -e

user_culti=`who|head -1|awk -F" " '{print $1}'`
group_culti=`who|head -1|awk -F" " '{print $1}'|xargs id -gn`
home=`egrep "^$user_culti" /etc/passwd|awk -F":" '{print $6}'`

# Test of the connection:
/Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 cultibox -e "SELECT * FROM  configuration;" > /dev/null 2>&1
if [ $? -eq 0 ]; then
        result=`/Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 --batch cultibox -e "SELECT VERSION FROM configuration;"`
        for res in `echo $result`; do
            if [ "`echo $res|egrep [1-9].*\.[1-9].*\.[1-9].*-.*`" != "" ]; then
                echo $res
                exit 0
            fi
        done
else
        exit 1
fi
exit 0
EOF
   if [ -d /Applications/cultibox ]; then
      /Applications/cultibox/xamppfiles/xampp stop
      sleep 4

      if [ -d /tmp/cultibox_backup ]; then
        rm -Rf /tmp/cultibox_backup
      fi

      mkdir -p /tmp/cultibox_backup
      
      cp -R /Applications/cultibox/xamppfiles/var/mysql/ibdata* /tmp/cultibox_backup/
      cp -R /Applications/cultibox/xamppfiles/var/mysql/ib_logfile* /tmp/cultibox_backup/
 
      touch /tmp/cultibox_upgrade
    fi
fi
