#!/bin/bash

set -x

if [ -f /Applications/XAMPP/xamppfiles/backup.sh ]; then
    /Applications/XAMPP/xamppfiles/backup.sh
    if [ $? -ne 0 ]; then
        echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting"
        exit 1
    fi
    /etc/init.d/cultibox stop
fi

if [ -f /Applications/XAMPP/xamppfiles/get_version.sh ]; then
    if [ -f /tmp/cultibox_version ]; then
        rm /tmp/cultibox_version
    fi
    /Applications/XAMPP/xamppfiles/get_version.sh > /tmp/cultibox_version
fi

exit 0

