#!/bin/bash

if [ -f /Applications/cultibox/xamppfiles/etc/php.ini ] && [ -f  /Applications/cultibox/xamppfiles/xampp ] && [ -d  /Applications/cultibox ]; then
    /Applications/cultibox/xamppfiles/xampp start
    sleep 6

    # Upgrade case:
    if [ -f /Applications/cultibox/run/get_version.sh ]; then
        if [ -f /tmp/cultibox_version ]; then
            rm /tmp/cultibox_version
        fi
        /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
    fi
    touch /tmp/cultibox_upgrade

   if [ -f /Applications/cultibox/run/backup.sh ]; then
        /Applications/cultibox/run/backup.sh
        if [ $? -ne 0 ]; then
            echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting ===="
            exit 1
        fi
    fi
fi
