#! /bin/sh
### BEGIN INIT INFO
# Provides:          cultipi
# Required-Start:    $all 
# Required-Stop:     $all 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start cultipi daemon at boot time
# Description:       Enable cultipi service provided by daemon.
### END INIT INFO


PATH="/sbin:/bin:/usr/sbin:/usr/bin" 

DAEMON="/usr/bin/cultipi"         
DAEMONUSER="root"
DEAMON_NAME="cultipi"

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting system $DEAMON_NAME Daemon"
        /usr/bin/tclsh "/opt/cultipi/cultiPi/cultiPi.tcl" "/etc/cultipi"&
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $DEAMON_NAME Daemon"
        for pid in "`ps aux|grep $DEAMON_NAME|grep tcl |awk -F \" \" '{print $2}'`"; do
            if [ "$pid" != "" ]; then
                kill -9 $pid
            fi
        done
        log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
                d_stop
                ;;

        status)
                if [ "`ps aux|grep cultipi|grep tclsh`" != "" ]; then
                    echo "[ ok ] $DEAMON_NAME service is running..."
                else 
                    echo "[ fail ] $DEAMON_NAME service is not running..."
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
