#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    update-rc.d cultipi defaults
    /etc/init.d/cultipi restart
fi

if [ -f /etc/cron.daily/cultipi ]; then
    chmod +x /etc/cron.daily/cultipi
fi


if [ "`cat /etc/crontab|grep cultipi`" == "" ]; then
    echo "*/1 *   * * *   root    source /etc/default/culticron . ; if [ "\$CULTICRON_ACTIV" == "yes" ]; then /etc/init.d/cultipi status >/dev/null; if [ \$? -ne 0 ]; then /etc/init.d/cultipi force-reload; fi fi" >> /etc/crontab
fi


