#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    update-rc.d cultipi defaults
    /etc/init.d/cultipi restart
fi

if [ -f /etc/cron.daily/cultipi ]; then
    chmod +x /etc/cron.daily/cultipi
fi


if [ "`cat /etc/crontab|grep culticron`" == "" ]; then
    echo "*/1 *   * * *   root    /bin/bash /etc/default/culticron" >> /etc/crontab
fi


