#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ "`ps ax|grep cultiPi.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep cultiPi.tcl|grep tclsh|awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done

        for pid in "`ps ax|grep serveurLog.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
            if [ "$pid" != "" ]; then
                kill -9 $pid
            fi
        done

        for pid in "`ps ax|grep serverPlugUpdate.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
            if [ "$pid" != "" ]; then
                kill -9 $pid
            fi
        done

        for pid in "`ps ax|grep serverHisto.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
            if [ "$pid" != "" ]; then
                kill -9 $pid
            fi
        done
    fi

    if [ -d /opt/cultipi ]; then
        rm -Rf /opt/cultipi
    fi

    if [ -d /etc/cultipi ]; then
        rm -Rf /etc/cultipi
    fi

    update-rc.d -f cultipi remove >/dev/null 2>&1

    if [ -f /etc/init.d/cultipi ]; then
        rm -Rf /etc/init.d/cultipi
    fi

    if [ -d /var/log/cultipi ]; then
        rm -Rf /var/log/cultipi
    fi

    if [ -f /etc/default/culticron ]; then
        rm /etc/default/culticron
    fi

    sed -i "/.*\/etc\/init.d\/culticron.*/d" /etc/crontab

    rm -Rf /etc/cultipi/conf_tmp
fi

if [ "$1" == "remove" ]; then
    update-rc.d -f cultipi remove > /dev/null 2>&1 

    if [ -f /etc/init.d/cultipi ]; then
        rm -Rf /etc/init.d/cultipi
    fi

    sed -i "/.*\/etc\/init.d\/culticron.*/d" /etc/crontab

    if [ -d /opt/cultipi ]; then
        rm -Rf /opt/cultipi
    fi

    rm -Rf /etc/cultipi/conf_tmp
fi

