#!/bin/bash
set -x

if [ -f /etc/init.d/cultipi ]; then
    update-rc.d cultipi defaults
fi

if [ ! -d /etc/cultipi/conf_tmp ]; then
    mkdir /etc/cultipi/conf_tmp
fi

if [ -d /etc/cultipi/conf_tmp/logs ]; then
    rm -Rf /etc/cultipi/conf_tmp/logs
fi

if [ -d /etc/cultipi/conf_tmp/cnf ]; then
    rm -Rf /etc/cultipi/conf_tmp/cnf
fi

if [ -d /etc/cultipi/conf_tmp/bin ]; then
    rm -Rf /etc/cultipi/conf_tmp/bin
fi

if [ -f /etc/cultipi/conf_tmp.log.txt ]; then
    rm /etc/cultipi/conf_tmp.log.txt
fi


if [  "`cat /etc/sudoers|grep cultipi|grep shutdown`" == "" ]; then
    echo "cultipi ALL = (root) NOPASSWD: /sbin/shutdown" >> /etc/sudoers
fi


chown -R www-data:www-data /etc/cultipi/conf_tmp
chown -R cultipi:cultipi /var/log/cultipi
chmod 755 /var/log/cultipi

find /etc/cultipi/ -name "*-dist"|xargs rm 2>/dev/null; echo ""

/etc/init.d/cultipi force-reload
