#!/bin/bash

if [ -f /etc/init.d/cultipi ]; then
    /etc/init.d/cultipi stop
    sleep 2

    # Killing remaining process:
    if [ "`ps ax|grep cultiPi.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep cultiPi.tcl| grep tclsh| awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then            
                kill -9 $process
            fi
        done
    fi
fi

if [ ! -d /var/log/cultipi ]; then
    mkdir /var/log/cultipi
    chown cultipi:cultipi /var/log/cultipi
fi

exit 0
